server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg-db-demo
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate #create-drop #update #create #none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false